services:
  elt_app:
    build: ./etl_project
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./data/gold:/app/data/gold
    networks:
      - elt_network

  postgres:
    image: postgres:16
    container_name: postgres_bootcamp
    restart: unless-stopped
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./db/create-db-schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: project_1
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - elt_network

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin_bootcamp
    restart: unless-stopped
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - elt_network

networks:
  elt_network:
volumes:
  postgres_data:
