services:
  postgres:
    image: postgres:16
    container_name: postgres_local
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .env
    environment:
      # POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin_local
    restart: unless-stopped
    ports:
      - "127.0.0.1:5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    # volumes:
    # - /Users/gabriel/Desktop/bootcamp/volume:/var/lib/pgadmin/storage/
    depends_on:
      - postgres
